abuse/urls.py
from django.urls import path, re_path, include

from . import views
from constants.base import EXTENSION_SLUGS_PATH

app_name = 'abuse'
urlpatterns = [
    path('abuse/reports/<int:pk>/', views.ReportView.as_view(), name='view-report'),
    re_path(
        rf'^(?P<type_slug>{EXTENSION_SLUGS_PATH})/',
        include(
            [
                path(
                    '<slug:slug>/report/',
                    views.ReportExtensionView.as_view(),
                    name='report-extension',
                ),
            ],
        ),
    ),
    # TODO: report user view and URL
]

blender_extensions/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.flatpages import views as flatpages_views
from django.urls import path, include, re_path
from django.views.static import serve
from django.views.generic.base import RedirectView

from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

import blender_id_oauth_client.urls

import common.views.errors

admin.site.enable_nav_sidebar = False
admin.site.site_header = settings.ADMIN_SITE_HEADER

urlpatterns = [
    path('oauth/', include(blender_id_oauth_client.urls)),
    path('admin/', include('loginas.urls')),
    path('admin/', admin.site.urls),
    path('', include('ratings.urls')),
    path('', include('extensions.urls')),
    path('', include('abuse.urls')),
    path('', include('users.urls')),
    path('', include('teams.urls')),
    path('', include('reviewers.urls')),
    path('api/swagger/', RedirectView.as_view(url='/api/v1/swagger/')),
    path('api/v1/', SpectacularAPIView.as_view(), name='schema_v1'),
    path('api/v1/swagger/', SpectacularSwaggerView.as_view(url_name='schema_v1'), name='swagger'),
    # Flatpages
    path('about/', flatpages_views.flatpage, {'url': '/about/'}, name='flatpage-about'),
    re_path(r'^(?P<url>.*/)$', flatpages_views.flatpage),
]
handler400 = common.views.errors.ErrorView.as_view(status=400)
handler403 = common.views.errors.ErrorView.as_view(status=403)
handler404 = common.views.errors.ErrorView.as_view(status=404)
handler500 = common.views.errors.ErrorView.as_view(status=500)

if settings.DEBUG:
    urlpatterns += [
        re_path(
            r'^media/(?P<path>.*)$',
            serve,
            {
                'document_root': settings.MEDIA_ROOT,
            },
        ),
        path('__debug__/', include('debug_toolbar.urls')),
    ]

extensions/urls.py
from django.urls import path, re_path, include, reverse_lazy
from django.views.generic import RedirectView

from constants.base import EXTENSION_SLUGS_PATH
from extensions.views import api, public, submit, manage

app_name = 'extensions'
urlpatterns = [
    path('submit/', submit.UploadFileView.as_view(), name='submit'),
    path('submit/<int:pk>/', submit.SubmitFileView.as_view(), name='submit-finalise'),
    # TODO: move /accounts pages under its own app when User model is replaced
    path('accounts/extensions/', manage.ManageListView.as_view(), name='manage-list'),
    # FIXME: while there's no profile page, redirect to My Extensions instead
    path(
        'accounts/profile/',
        RedirectView.as_view(url=reverse_lazy('extensions:manage-list'), permanent=False),
    ),
    # API
    path('api/v1/extensions/', api.ExtensionsAPIView.as_view(), name='api'),
    # Public pages
    path('', public.HomeView.as_view(), name='home'),
    path('', api.ExtensionsAPIView.as_view(), name='home-api'),
    path('search/', public.SearchView.as_view(), name='search'),
    path('author/<int:user_id>/', public.SearchView.as_view(), name='by-author'),
    path('search/', public.SearchView.as_view(), name='search'),
    path('tag/<slug:tag_slug>/', public.SearchView.as_view(), name='by-tag'),
    path('team/<slug:team_slug>/', public.SearchView.as_view(), name='by-team'),
    re_path(
        rf'^(?P<type_slug>{EXTENSION_SLUGS_PATH})/$',
        public.SearchView.as_view(),
        name='by-type',
    ),
    # Pages for maintainers
    re_path(
        rf'^(?P<type_slug>{EXTENSION_SLUGS_PATH})/',
        include(
            [
                path(
                    '<slug:slug>/manage/',
                    manage.UpdateExtensionView.as_view(),
                    name='manage',
                ),
                path(
                    '<slug:slug>/manage/versions/',
                    manage.ManageVersionsView.as_view(),
                    name='manage-versions',
                ),
                path(
                    '<slug:slug>/manage/versions/new/',
                    manage.NewVersionView.as_view(),
                    name='new-version',
                ),
                path(
                    '<slug:slug>/manage/versions/new/<int:pk>/',
                    manage.NewVersionFinalizeView.as_view(),
                    name='new-version-finalise',
                ),
                path(
                    '<slug:slug>/manage/versions/<int:pk>/delete/',
                    manage.VersionDeleteView.as_view(),
                    name='version-delete',
                ),
                path(
                    '<slug:slug>/manage/versions/<int:pk>/update/',
                    manage.UpdateVersionView.as_view(),
                    name='version-update',
                ),
                path(
                    '<slug:slug>/<version>/download/',
                    public.extension_version_download,
                    name='version-download',
                ),
                path('<slug:slug>/versions/', manage.VersionsView.as_view(), name='versions'),
                path('<slug:slug>/', manage.ExtensionDetailView.as_view(), name='detail'),
            ],
        ),
    ),
]

files/models.py
from pathlib import Path
from typing import Dict, Any
import logging
import mimetypes
import re

from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

# from taggit.models import Tag

from common.model_mixins import CreatedModifiedMixin, TrackChangesMixin, SoftDeleteMixin
from files.utils import get_sha256
from constants.base import (
    FILE_STATUS_CHOICES,
    FILE_TYPE_CHOICES,
)
import utils

User = get_user_model()
log = logging.getLogger(__name__)


class FileManager(models.Manager):
    @property
    def listed(self):
        return self.filter(status=self.model.STATUSES.APPROVED)

    @property
    def unlisted(self):
        return self.exclude(status=self.model.STATUSES.APPROVED)


def file_upload_to(instance, filename):
    prefix = 'files/'
    if instance.is_image:
        prefix = 'images/'
    elif instance.is_video:
        prefix = 'videos/'

    _hash = instance.hash.split(':')[-1]
    extension = Path(filename).suffix
    path = Path(prefix, _hash[:2], _hash).with_suffix(extension)
    return path


def thumbnail_upload_to(instance, filename):
    prefix = 'thumbnails/'
    _hash = instance.hash.split(':')[-1]
    extension = Path(filename).suffix
    path = Path(prefix, _hash[:2], _hash).with_suffix(extension)
    return path


class File(CreatedModifiedMixin, TrackChangesMixin, SoftDeleteMixin, models.Model):
    track_changes_to_fields = {'status', 'size_bytes', 'hash', 'date_deleted'}

    TYPES = FILE_TYPE_CHOICES
    STATUSES = FILE_STATUS_CHOICES

    date_approved = models.DateTimeField(null=True, blank=True, editable=False)
    date_status_changed = models.DateTimeField(null=True, blank=True, editable=False)

    source = models.FileField(null=False, blank=False, upload_to=file_upload_to)
    thumbnail = models.ImageField(
        upload_to=thumbnail_upload_to,
        null=True,
        blank=True,
        max_length=256,
        help_text='Image thumbnail in case file is a video',
    )
    content_type = models.CharField(max_length=256, null=True, blank=True)
    type = models.PositiveSmallIntegerField(
        choices=TYPES,
        null=True,
        blank=True,
        help_text=(
            'Indicates that this is an image, a video '
            'or a type of extension this file appears to match, '
            'as guessed from its contents.'
        ),
    )
    status = models.PositiveSmallIntegerField(choices=STATUSES, default=STATUSES.APPROVED)

    user = models.ForeignKey(
        User, related_name='files', null=False, blank=False, on_delete=models.CASCADE
    )
    size_bytes = models.PositiveBigIntegerField(default=0, editable=False)
    hash = models.CharField(max_length=255, null=False, blank=True, unique=True)
    original_name = models.CharField(max_length=255, blank=True, null=False)
    original_hash = models.CharField(
        max_length=255,
        null=False,
        blank=True,
        unique=True,
        help_text='The original hash of the file before we repackage it any way.',
    )

    metadata = models.JSONField(
        null=False,
        default=dict,
        blank=True,
        # TODO add link to the manifest file user manual page.
        help_text=('Meta information that was parsed from the `manifest file.'),
    )

    objects = FileManager()

    def __str__(self) -> str:
        return f'{self.original_name} ({self.get_status_display()})'

    @property
    def has_been_validated(self):
        try:
            self.validation
        except FileValidation.DoesNotExist:
            return False
        else:
            return True

    @classmethod
    def generate_hash(self, source):
        """Generate a hash for the File"""
        return f'sha256:{get_sha256(source)}'

    @property
    def file_path(self):
        return self.source.path if self.source else ''

    @property
    def filename(self):
        return self.source.name if self.source else ''

    def save(self, *args, **kwargs):
        """Set values that depend of the source file (size, original hash and name)."""
        if not self.size_bytes:
            self.size_bytes = self.source.size
        if not self.original_name:
            self.original_name = self.source.name

        if not self.content_type:
            content_type, _ = mimetypes.guess_type(self.original_name)
            self.content_type = content_type
        if self.content_type:
            if 'image' in self.content_type:
                self.type = self.TYPES.IMAGE
            if 'video' in self.content_type:
                self.type = self.TYPES.VIDEO

        if not self.original_hash or not self.hash:
            _hash = self.generate_hash(self.source)
            self.original_hash = _hash or self.original_hash
            self.hash = _hash or self.hash

        self.full_clean()
        return super().save(*args, **kwargs)

    def is_listed(self):
        return self.status == self.model.STATUSES.APPROVED

    @property
    def is_image(self) -> bool:
        return self.type == self.TYPES.IMAGE

    @property
    def is_video(self) -> bool:
        return self.type == self.TYPES.VIDEO

    @property
    def suffix(self) -> str:
        path = Path(self.source.path)
        return ''.join(path.suffixes)

    @property
    def extension(self):
        return self.version.extension

    @property
    def parsed_extension_fields(self) -> Dict[str, Any]:
        """Return Extension-related data that was parsed from file's content."""
        data = self.metadata

        extension_id = data.get('id')
        original_name = data.get('name', self.original_name)
        name_as_path = Path(original_name)
        for suffix in name_as_path.suffixes:
            original_name = original_name.replace(suffix, '')
        name = re.sub(r'[-_ ]+', ' ', original_name)
        return {
            'name': name,
            'slug': utils.slugify(name),
            'extension_id': extension_id,
            'website': data.get('website'),
        }

    @property
    def parsed_version_fields(self) -> Dict[str, Any]:
        """Return Version-related data that was parsed from file's content."""
        # Currently, the content of the manifest file is the only
        # kind of file metadata that is supported.
        data = self.metadata
        return {
            'version': data.get('version'),
            'tagline': data.get('tagline'),
            'blender_version_min': data.get('blender_version_min'),
            'schema_version': data.get('schema_version'),
            'licenses': data.get('license'),
            'permissions': data.get('permissions'),
            'tags': data.get('tags'),
        }

    def get_submit_url(self) -> str:
        return reverse('extensions:submit-finalise', kwargs={'pk': self.pk})


class FileValidation(CreatedModifiedMixin, TrackChangesMixin, models.Model):
    track_changes_to_fields = {'is_valid', 'errors', 'warnings', 'notices', 'validation'}

    file = models.OneToOneField(File, related_name='validation', on_delete=models.CASCADE)
    is_valid = models.BooleanField(default=False)
    errors = models.IntegerField(default=0)
    warnings = models.IntegerField(default=0)
    notices = models.IntegerField(default=0)
    validation = models.TextField()

extensions/views/api.py
import logging

from rest_framework.response import Response
from rest_framework import serializers
from rest_framework.views import APIView
from drf_spectacular.utils import OpenApiParameter, extend_schema

from common.compare import is_in_version_range
from extensions.models import Extension
from extensions.utils import clean_json_dictionary_from_optional_fields


from constants.base import (
    EXTENSION_TYPE_SLUGS_SINGULAR,
)

log = logging.getLogger(__name__)


class ListedExtensionsSerializer(serializers.ModelSerializer):
    class Meta:
        model = Extension
        fields = ()

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        self.blender_version = kwargs.pop('blender_version', None)
        super().__init__(*args, **kwargs)

    def to_representation(self, instance):
        blender_version_min = instance.latest_version.blender_version_min
        blender_version_max = instance.latest_version.blender_version_max

        # TODO: get the latest valid version
        # For now we skip the extension if the latest version is not in a valid range.
        if self.blender_version and not is_in_version_range(
            self.blender_version, blender_version_min, blender_version_max
        ):
            return {}

        data = {
            'schema_version': instance.latest_version.schema_version,
            'id': str(instance.id),
            'name': instance.name,
            'version': instance.latest_version.version,
            'tagline': instance.latest_version.tagline,
            'archive_hash': instance.latest_version.file.original_hash,
            'archive_size': instance.latest_version.file.size_bytes,
            'archive_url': self.request.build_absolute_uri(instance.latest_version.download_url),
            'type': EXTENSION_TYPE_SLUGS_SINGULAR.get(instance.type),
            'blender_version_min': instance.latest_version.blender_version_min,
            'blender_version_max': instance.latest_version.blender_version_max,
            'website': self.request.build_absolute_uri(instance.get_absolute_url()),
            'maintainer': str(instance.authors.first()),
            'license': [
                license_iter.slug for license_iter in instance.latest_version.licenses.all()
            ],
            'permissions': [
                permission.slug for permission in instance.latest_version.permissions.all()
            ],
            # TODO: handle copyright
            'tags': [str(tag) for tag in instance.latest_version.tags.all()],
        }

        # TODO: temp hack until Blender fixes that
        if not data['tags']:
            data['tags'] = ['Unassigned']

        return {instance.extension_id: clean_json_dictionary_from_optional_fields(data)}


class ExtensionsAPIView(APIView):
    serializer_class = ListedExtensionsSerializer

    @staticmethod
    def _convert_list_to_dict(data):
        return {k: v for d in data for k, v in d.items()}

    @extend_schema(
        parameters=[
            OpenApiParameter(
                name="blender_version",
                description=("Blender version to check for compatibility"),
                type=str,
            )
        ]
    )
    def get(self, request):
        blender_version = request.GET.get('blender_version')
        serializer = self.serializer_class(
            Extension.objects.listed, blender_version=blender_version, request=request, many=True
        )
        data_as_dict = self._convert_list_to_dict(serializer.data)
        return Response(data_as_dict)

extensions/templates/extensions/components/authors.html
{# Indentation looks like this so there is no gap between the author name and comma. #}
{% for author in extension.authors.all %}{% if forloop.counter > 1 %},&nbsp;{% endif %}<a href="{% url "extensions:by-author" user_id=author.pk %}" title="{{ author }}">{{ author }}</a>{% endfor %}

extensions/templates/extensions/components/badge_support.html
<a href="{% url "extensions:by-support" support_slug=slug %}" title="Support: {{ name }}"
  class="badge text-decoration-none align-middle {% if not small %}px-3 py-2 my-1{% endif %} badge-dark{#% if slug == 'official' %}primary{% elif slug == 'community' %}success{% else %}warning{% endif % #}"
  style="{% if not small %}font-size: var(--font-size-base);{% endif %}">
  <b>{{ name }}</b>
</a>

extensions/templates/extensions/components/badge_tag.html
{% load extensions %}

<a href="{% url "extensions:by-tag" tag_slug=tag.slug %}" title="{{ tag.name }}"
  class="badge badge-tag{% if not small %} badge-lg{% endif %} {{ class }}">
  {{ tag.name }}
</a>

extensions/templates/extensions/components/blender_version.html
{% load i18n common %}

<a
  href="https://www.blender.org/download/releases/{{ version.blender_version_min|version_without_patch|replace:".,-" }}/"
  title="{{ version.blender_version_min }}">Blender {{ version.blender_version_min|version_without_patch }}</a>
{% if version.blender_version_max %}
{% if version.blender_version_max|version_without_patch != version.blender_version_min|version_without_patch %}
  &mdash;
  <a
    href="https://www.blender.org/download/releases/{{ version.blender_version_max|version_without_patch|replace:".,-" }}/"
    title="{{ version.blender_version_max }}">{{ version.blender_version_max|version_without_patch }}</a>
  {% endif %}
{% else %}
  {% trans 'and newer' %}
{% endif %}

extensions/templates/extensions/components/card.html
{% load common filters %}
{% with latest=extension.latest_version %}

<div class="ext-card {% if blur %}is-background-blur{% endif %}">
  {% if blur %}
  <div class="ext-card-thumbnail-blur" style="background-image: url({{ extension.previews.listed.first.source.url }});"></div>
  {% endif %}

  <a class="ext-card-thumbnail" href="{{ extension.get_absolute_url }}">
    <div class="ext-card-thumbnail-img" style="background-image: url({{ extension.previews.listed.first.source.url }});" title="{{ extension.name }}"></div>
  </a>

  <div class="ext-card-body">
    <h3 class="ext-card-title">
      <a href="{{ extension.get_absolute_url }}">{{ extension.name }}</a>
    </h3>
    <p>
      {{ latest.tagline }}
    </p>

    <ul class="ext-list-details">
      <li class="ext-card-author">
      {% if extension.team %}
        {% with team=extension.team %}
        <a href="{{ team.get_absolute_url }}" title="{{ team.name }}">{{ team.name }}</a>
        {% endwith %}
      {% elif extension.authors.count %}
        {% include "extensions/components/authors.html" %}
      {% endif %}
      </li>
      {% if latest.tags.count %}
      <li class="ext-card-tags">
        {% include "extensions/components/tags.html" with small=True version=latest %}
      </li>
      {% endif %}
    </ul>
    <ul class="ext-list-details">
      {% if extension.average_score %}
      <li>
        {% include "ratings/components/average.html" with score=extension.average_score %}
      </li>
      {% endif %}

      {% if extension.download_count %}
      <li title="{{ extension.download_count }} downloads">
        <i class="i-download"></i> {{ extension.download_count | int_compact }}
      </li>
      {% endif %}

      {% if show_type %}
      <li class="ml-auto">
        {{ extension.get_type_display }}
      </li>
      {% endif %}
    </ul>
  </div>

  {# Author/admin tools can be added here in an extending template #}
  {% block admin %}{% endblock admin %}
</div>
{% endwith %}

extensions/templates/extensions/components/categories.html
{% load i18n %}
<div class="card p-3 mb-3">
  <div class="card-header mx-3">
    <h2 class="card-title">{% trans 'Categories' %}</h2>
  </div>
  <div class="card-body m-3">
    <div class="card-text text-center">
      {% for category in categories %}
        {% include "extensions/components/category.html" %}
      {% endfor %}
    </div>
  </div>
</div>

extensions/templates/extensions/components/detail_card_version_permissions.html
<div class="ext-detail-permissions">
  <dt>Permissions</dt>
  {% if version.permissions.all %}
  <dd>This version requests the following:
  <ul>
    {% for p in version.permissions.all %}
    <li>
      <div>
        <i class="i-permission-{{ p.slug }}"></i>
      </div>
      <div>
        <strong>{{ p.name }}</strong>
        <small>{{ p.help }}</small>
      </div>
    </li>
    {% endfor %}
  </ul>
  </dd>
  {% else %}
  <dd>No special permissions required.</dd>
  {% endif %}
</div>

extensions/templates/extensions/components/extension_edit_detail_card.html
{% load i18n common %}

{# Info Summary #}
<section class="ext-detail-info">
  <div class="card">
    {% if is_initial %}
    <div class="badge badge-info card-badge">
      Information retrieved from manifest
    </div>
    {% else %}
    <div class="dl-row px-3 pt-3">
      <div class="dl-col mb-0">
        <dt>{% trans 'Approval Status' %}</dt>
        <dd>{% include "common/components/status.html" with object=extension %}</dd>
      </div>
    </div>
    {% endif %}
    <div class="p-3">
      <dl>
        <div class="dl-row">
          <div class="dl-col">
            {% if extension.authors.count %}
            <dt>{% trans 'Developers' %}</dt>
            <dd>{% include "extensions/components/authors.html" %}</dd>
            {% endif %}
          </div>
        </div>

        <div class="dl-row">
          <div class="dl-col">
            <dt>{% trans 'Name' %}</dt>
            <dd>{{ extension.name }}</dd>
          </div>
        </div>

        <div class="dl-row">
          <div class="dl-col">
            <dt>{% trans 'Tagline' %}</dt>
            <dd title="{{ latest.tagline }}">{{ latest.tagline }}</dd>
          </div>
        </div>

        <div class="dl-row">
          <div class="dl-col">
            <dt>{% trans 'Version' %}</dt>
            <dd>
              <a href="{{ extension.get_versions_url }}">
              {{ latest.version }}
              </a>
            </dd>
          </div>
          <div class="dl-col">
            <dt>{% trans 'Size' %}</dt>
            <dd>{{ latest.file.size_bytes|filesizeformat }}</dd>
          </div>
        </div>

        <div class="dl-row">
          <div class="dl-col">
            <dt>{% trans 'Compatibility' %}</dt>
            <dd>{% include "extensions/components/blender_version.html" with version=latest %}</dd>
          </div>
        </div>

        {% if extension.website %}
        <div class="dl-row">
          <div class="dl-col">
            <dt>{% trans 'Website' %}</dt>
            <dd>{% include "common/components/external_link.html" with url=extension.website show_path=True %}</dd>
          </div>
        </div>
        {% endif %}

        <div class="dl-row">
          <div class="dl-col">
            <dt>License{{ latest.licenses.count|pluralize }}</dt>
            {% for license in latest.licenses.all %}
            <dd>
              {% include "common/components/external_link.html" with url=license.url title=license %}
            </dd>
            {% endfor %}
          </div>
        </div>

        <div class="dl-row">
          <div class="dl-col">
            {% include "extensions/components/detail_card_version_permissions.html" with version=latest %}
          </div>
        </div>

        <div class="dl-row">
          <dd>
            {% if latest.tags.count %}
            {% include "extensions/components/tags.html" with small=True version=latest %}
            {% else %}
            No tags.
            {% endif %}
          </dd>
        </div>
      </dl>
    </div>
  </div>
</section>

extensions/templates/extensions/components/galleria.html
{% with previews=extension.get_previews %}
<section class="galleria-container" id="galleria-container">
  {% if previews %}
  <div class="galleria-items{% if previews.count > 5 %} is-many{% endif %}{% if previews.count == 1 %} is-single{% endif %}" id="galleria-items">
    {% for preview in previews %}
    <a
      class="galleria-item js-galleria-item-preview galleria-item-type-{{ preview.content_type|slugify|slice:5 }}{% if forloop.first %} is-active{% endif %}"
      href="{{ preview.source.url }}"
      {% if 'video' in preview.content_type %}data-galleria-video-url="{{ preview.source.url }}"{% endif %}
      data-galleria-content-type="{{ preview.content_type }}"
      data-galleria-index="{{ forloop.counter }}">

        {% if 'video' in preview.content_type and preview.thumbnail %}
        <img src="{{ preview.thumbnail.url }}" alt="{{ preview.extension_preview.first.caption }}">
        {% else %}
        <img src="{{ preview.source.url }}" alt="{{ preview.extension_preview.first.caption }}">
        {% endif %}
      </a>
    {% endfor %}
  </div>
  {% else %}
  <div class="galleria-item is-empty">
    <div>
      No preview yet.
      {% if is_maintainer %}
      <a class="btn btn-primary px-5" href="{{ extension.get_manage_url }}#previews">Add a Preview</a>
      {% endif %}
    </div>
  </div>
  {% endif %}
</section>
{% endwith %}

extensions/templates/extensions/components/tags.html
{% for tag in version.tags.all %}
{% include "extensions/components/badge_tag.html" %}
{% endfor %}